name: first_testing

on: [push]

jobs:
  first_job1:
    name: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name : install python 
        run : pip install pandas
      - name : install databricks cli
        run : curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name : check the datbrick cli version
        run : databricks version



  second_job2:
    name: second_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
